# 1. Write a program to store seven fruits in a list entered by the user.



# 2. Write a program to accept marks of 6 students and display them in a sorted

fruits = []

f1 = input("Enter Fruit name: ")
fruits.append(f1)
f2 = input("Enter Fruit name: ")
fruits.append(f2)
f3 = input("Enter Fruit name: ")
fruits.append(f3)
f4 = input("Enter Fruit name: ")
fruits.append(f4)
f5 = input("Enter Fruit name: ")
fruits.append(f5)
f6 = input("Enter Fruit name: ")
fruits.append(f6)
f7 = input("Enter Fruit name: ")
fruits.append(f7)

print(fruits)

# manner.



# 3. Check that a tuple type cannot be changed in python.



# 4. Write a program to sum a list with 4 numbers.



# 5. Write a program to count the number of zeros in the following tuple: